### ISSUE TITLE
Support for OpenStack Swift

### ISSUE THREAD

**Issue by bgagnon** [mathcamp/pypicloud#28]
I think this can be achieved either through the [native Swift Object Storage API]( http://docs.openstack.org/api/openstack-object-storage/1.0/content/) or the [S3 compatibility API](http://docs.openstack.org/grizzly/openstack-object-storage/admin/content/configuring-openstack-object-storage-with-s3_api.html). This would make pypicloud suitable for private clouds.

**Comment by ahmet2mir** [comment]
@bgagnon I think that you could use the S3 Compatible storage PR#72

- https://pypicloud.readthedocs.io/en/latest/topics/storage.html#storage-host
- https://pypicloud.readthedocs.io/en/latest/topics/storage.html#storage-is-secure
- https://pypicloud.readthedocs.io/en/latest/topics/storage.html#storage-calling-format

**Comment by stevearc** [comment]
Thanks for the bump!
