### ISSUE TITLE
Non-standard names are not shown on index page

### ISSUE THREAD

**Issue by a-tal** [mathcamp/pypicloud#46]
During testing, I noticed that if a project uses non-pep440 compliant version names, they don't appear on the index page. pip does the right thing still as far as determining the correct newest package, but it'd be nice if the index had the same info.

Crop of main index page:
![index](https://cloud.githubusercontent.com/assets/1832772/7398201/6facd572-ee62-11e4-90eb-79ee8a664c06.png)

project file listing:
![project](https://cloud.githubusercontent.com/assets/1832772/7398202/6fae4330-ee62-11e4-93d2-f40ed21e838c.png)

**Comment by stevearc** [comment]
I'm looking into this. It's probably a simple fix, but I'm getting sidetracked by some other weird behavior

**Comment by stevearc** [comment]
I can't seem to reproduce this problem. Can you confirm that you are using 0.2.10 and paste your config file up here? Also, are you uploading via `python setup.py sdist upload` or the web interface?

**Comment by a-tal** [comment]
Yep this is with 0.2.10; here's my test config:

<pre>[app:main]
use = egg:pypicloud

pyramid.reload_templates = False
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en


# storage
pypi.storage = s3
storage.access_key = *****
storage.secret_key = *****
storage.bucket = *****
storage.prepend_hash = False

# cache
db.url = sqlite:///%(here)s/db.sqlite

# auth
auth.admins =
  adam

user.adam = *****

pypi.default_read = everyone
pypi.default_write = everyone


# For beaker
session.encrypt_key = *****
session.validate_key = *****
session.secure = False

###
# wsgi server configuration
###

[uwsgi]
paste = config:%p
paste-logger = %p
socket = 127.0.0.1:3031
master = true
processes = 20
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 1000
enable-threads = true
virtualenv = /home/ec2-user/pypicloud

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root

[handlers]
keys = file

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = file

[handler_file]
class = handlers.RotatingFileHandler
args = ('/var/log/pypicloud.log', 'mode=a', 'maxBytes=1000000', 'backupCount=5')
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)s %(asctime)s [%(name)s] %(message)s</pre>

It was uploaded with `twine version 1.5.0 (pkginfo: 1.2.1, requests: 2.6.2, setuptools: 15.2)`

**Comment by stevearc** [comment]
For whatever reason I seem to be unable to reproduce this problem. What's the contents of the dummy package setup.py file? That's the only significant thing I can think of that might still be different.

**Comment by a-tal** [comment]
Sure, no worries, thanks for taking a look at this. Here's the entire dummy project:

`named_thing.py`
```python
import pkg_resources


def main():
    package = pkg_resources.get_distribution("named_thing")
    print("named_thing {} is installed".format(package.version))


if __name__ == "__main__":
    main()
```

`setup.py`
```python
from setuptools import setup


setup(
    name="named_thing",
    version="1.2.3.POTATO.3",
    py_modules=["named_thing"],
    entry_points={"console_scripts": ["named_thing = named_thing:main"]},
)
```

**Comment by stevearc** [comment]
Sorry, I just can't reproduce the bug. If you have any other clues for me, let me know, but for now I'm going to stop investigating.

**Comment by a-tal** [comment]
yeah it's fine. this is a non-issue.
