### ISSUE TITLE
URL changes result in 401 for easy_install

### ISSUE THREAD

**Issue by GarrettHeel** [mathcamp/pypicloud#54]
It looks like there was a recent change which caused the URLs for `https://<pypicloud>/pypi/<package>/` from pointing directly at the destination (in this case S3) to a subpath within `https://<pypicloud>`.

Unfortunately, this breaks installation via easy_install as the authentication specified in the `index-url` will be lost when following the redirect. This ends up presenting as a 401 during a `setup.py install` when fetching dependencies.

**Comment by stevearc** [comment]
Argh, sorry about that. I tested it with pip and it seemed to work, but historically python has some issues with basic auth and redirects. I'll dig into it and see if I can find a way to reasonably resolve it.

**Comment by GarrettHeel** [comment]
Thanks!
