### ISSUE TITLE
"python-logstash-0.4.5" package shows up as "python" with "logstash-0.4.5" as the version

### ISSUE THREAD

**Issue by bgagnon** [mathcamp/pypicloud#56]
I cannot upload this package from the public PyPI to my pypicloud instance:
https://pypi.python.org/simple/python-logstash/

**Comment by stevearc** [comment]
Thanks for the bug report! I have found the issue and I'll get to it soon.

**Comment by stevearc** [comment]
If you need a workaround, you'll notice that when you are uploading the package there is a text field with "python" in it. Just type "python-logstash" and then hit upload.
