### ISSUE TITLE
Mirror mode: only the first URL for each package is presented

### ISSUE THREAD

**Issue by robgolding63** [mathcamp/pypicloud#61]
When `mirror` mode is enabled, the `get_fallback_packages` function only presents the first URL for each of the packages available upstream (via [this `break` statement](https://github.com/mathcamp/pypicloud/blob/master/pypicloud/views/simple.py#L84)).

---

This can cause problems, because sometimes the first URL is a "wheel" package. Then, if the client uses `--no-use-wheel`, the package cannot be installed.

I don't have all the context required to make the call, but could that `break` line simply be removed?

**Comment by stevearc** [comment]
I'll have to dig into it, but I think removing the break might Just Work™

Could you tell me which package is failing so I can test this locally?

**Comment by robgolding63** [comment]
Sure, the package was `pyopenssl`. I was trying to install the latest version specifically (`0.15.1`) with `--no-use-wheel` enabled. `pypicloud` only presents `pyOpenSSL-0.15.1-py2.py3-none-any.whl` for that version, so it fails.

Thanks for looking into it! :smile:
