### ISSUE TITLE
Group access control setting for all packages

### ISSUE THREAD

**Issue by inirudebwoy** [mathcamp/pypicloud#65]
Hi,

We have pypicloud locally and push all Jenkin's builds to it. We have few users setup: 
- admin user for managing pypicloud
- jenkins user for uploading to pypicloud
- installation user that is used when installing packages

Admin user should have read/write access to all packages and should be able to manage groups, this is done by adding him to `auth.admins` in pypicloud config. 
Jenkins user should have read/write access to all packages but should not have administrator access. This could not be achieved, so temporarily we added him to `auth.admins`.
Installation user should have read only access to all packages, this has been achieved by creating user but not adding him to `auth.admins`.

I could not find information in docs about granting one user read/write access to every package. It is possible to specify exact packages you wish grant access to but this requires maintaining a list and keeping it up to date. Same applies to granting read only access to all packages in the pypicloud.

Do you have any recommendation on how to approach this?
Have I missed any feature in the docs that would allow creating such configuration?

**Comment by stevearc** [comment]
Yes, check the docs for [default_read and default_write](http://pypicloud.readthedocs.org/en/latest/topics/configuration.html#pypi-default-read). If you're using the `ini` file as your access backend, the file will look something like this:

```ini
# Give the 'jenkins' group write permissions on all packages with no explicit permissions
pypi.default_write =
    jenkins
# pypi.default_read defaults to 'authenticated'

# Define the users
user.admin = <password hash>
user.jenkins = <password hash>
user.installer = <password hash>

# Put the jenkins user in the 'jenkins' group
group.jenkins =
    jenkins

# Make the admin user an admin
auth.admins =
    admin
```

**Comment by inirudebwoy** [comment]
Thanks. This answers my question.
