### ISSUE TITLE
wsgi server configuration generation bug

### ISSUE THREAD

**Issue by fangyizhu** [mathcamp/pypicloud#83]
Hello, 
We generated prod.ini by running "ppc-make-config -p prod.ini"
Under [uwsgi], there's one line:
enable-threads = truesocket = 127.0.0.1:3031

It causes problem when running wsgi

We fixed it by putting a new line before socket:
enable-threads = true
socket = 127.0.0.1:3031

I've noticed another user have ran into the same problem:
https://github.com/mathcamp/pypicloud/issues/80

Looks like it's something to do with this template file, maybe add a new line in front of line 57? https://github.com/mathcamp/pypicloud/blob/master/pypicloud/templates/config.ini.jinja2

Please fix it. Thanks.

**Comment by stevearc** [comment]
That was fixed in #77 and will be included in the next release

**Comment by stevearc** [comment]
I released version [0.3.11](https://pypi.python.org/pypi/pypicloud/0.3.11) which has the fix
