### ISSUE TITLE
Configuration options need better explanation + examples

### ISSUE THREAD

**Issue by kevart** [mathcamp/pypicloud#85]
E.g. pypi.default_read: 

What is a group? 
Which options do I have? 
Is _authenticated_ a group?
What is the _syntax_ of a list?

I have tried:

```
pypi.default_read = everyone
pypi.default_write = everyone
```
and
```
pypi.default_read = ['everyone']
pypi.default_write = ['everyone']
```

in my config but pip still asks for username and password.

**Comment by stevearc** [comment]
Hi kevart

Have you seen the [Access Control](http://pypicloud.readthedocs.io/en/latest/topics/access_control.html) page and the [section on pypi.default_read](http://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-default-read) in the docs? It might answer some of those questions. I'll also knock out a few of them for you real quick

* **What is a group?** - A group is a collection of users.
* **Is `authenticated` a group?** - Yes. So is `everyone`. These are special groups that are always present.
* **Which options do I have?** - That's a big question, but as a summary you can grant read and write permissions to individual packages or, through the `pypi.default_read` and `pypi.default_write`, all packages.
* **What is the syntax of a list?** - Space separated, optionally with newlines for long lists
```
pypi.default_read = group1 group2 group3
pypi.default_write =
    group1
    group2
    group3
```

Lastly if you're still having issues please paste your full config file (redacting any sensitive information) and tell me exactly what operation you're attempting and what the behavior is that you're seeing.

**Comment by kevart** [comment]
Wow, thanks for the quick and detailed answer!! I think I should be fine with `everyone` and `authenticated` for now.

Here is my config file:

```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = False
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

pypi.default_read = everyone
pypi.default_write = everyone

pypi.storage = s3
storage.access_key = ****
storage.secret_key = ****
storage.bucket = ****

auth.admins = foo
user.foo = ****

# For beaker
session.encrypt_key = ****
session.validate_key = ****
session.secure = False

# fetch packages from official repository and store locally
pypi.fallback = cache

# additionally use redis as cache
pypi.db = redis
db.url = redis://localhost:6379/0

# show official packages even if not available locally
pypi.always_show_upstream = True

# allow users to overwrite packages
pypi.allow_overwrite = True

###
# wsgi server configuration
###

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
processes = 20
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 1000
enable-threads = true
socket = 127.0.0.1:3031
virtualenv = /env

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root, boto, pypicloud

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_pypicloud]
level = DEBUG
qualname = pypicloud
handlers =

[logger_boto]
level = WARN
qualname = boto
handlers =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)s %(asctime)s [%(name)s] %(message)s
```

and my ~/.pip/pip.conf

```
[global]

timeout = 60
index-url = https://192.168.99.100/simple
# can be removed after installing a proper ssl certificate
trusted-host = 192.168.99.100
```

When installing a package with pip I get asked for username and password although `pypi.default_read` is set to _everyone_.

Thanks again!

**Comment by stevearc** [comment]
I'll give this a run after work to see if I can reproduce it, but at a glance my guess would be that the package you're trying to install doesn't exist in pypicloud yet, and the `everyone` user isn't authenticated to update the cache. Try changing the [pypi.cache_update](http://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-cache-update) setting.

```
pypi.cache_update = everyone
```

**Comment by kevart** [comment]
I have tried 

`pypi.cache_update = everyone`

but got the same result.

**Comment by kevart** [comment]
`pypi.cache_update = everyone`

worked. I should have read the documentation more carefully. Thanks a lot again for your help!!

**Comment by pulecp** [comment]
I'm sorry for commenting in this pretty old thread but I will try that before I will open another issue.

I am not able to pass a list to `pypi.disallow_fallback`. I tried all options below but nothing works :(

```
pypi.disallow_fallback =
    package1
    package2
```

```
pypi.disallow_fallback = (package1, package2)
```

```
pypi.disallow_fallback = [package1, package2]
```

```
pypi.disallow_fallback = package1, package2
```
