### ISSUE TITLE
Web UI not showing packages with uWSGI

### ISSUE THREAD

**Issue by fangyizhu** [mathcamp/pypicloud#88]
Hello,
We've followed the documents to set up our Pypi server for production with uWSGI and nginx. 
We can upload and download packages without and problem through command line. But the web UI isn't showing any packages on S3 (even if I can successfully download them through pip install). 

Waitress server doesn't have this issue and shows all the packages properly.

We are using EC2 server, amazon ami. It seems like a front end issue to me.

**Comment by stevearc** [comment]
As a quick check, what did you set as `pypi.default_read` and are you logged in on the web client? My first guess is that this is a permissions issue. If not, I'll need to know more about your settings and users so I can try to reproduce the behavior.

**Comment by fangyizhu** [comment]
I tried adding pypi.default_read = everyone, solves the problem, thank you!
I suggest adding pypi.default_read = authenticated to prod.ini generation. 
It wasn't very clear why it didn't work.
