### ISSUE TITLE
Cannot upload to pypicloud

### ISSUE THREAD

**Issue by kevart** [mathcamp/pypicloud#90]
I can't upload custom packages to my pypicloud, uploading to the official pypitest repository works.

**.pypirc**

```
[distutils]
index-servers =
    pypicloud
    pypitest

[pypicloud]
repository=https://192.168.99.100/pypi
username=****
password=****

[pypitest]
repository=https://testpypi.python.org/pypi
username=****
password=****
```

_python setup.py register -r pypitest_ (official repo - works)
```
running register
running check
Registering **** to https://testpypi.python.org/pypi
```

_python setup.py register -r pypicloud_ (https)
```
running register
running check
Registering **** to https://192.168.99.100/pypi
Server response (500): <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

_python setup.py register -r pypicloud_ (changed .pypirc to use http)
```
running register
running check
Registering **** to http://192.168.99.100/pypi
Server response (400): Bad Request
```

I can't see any useful errors in pypicloud.log.
I can access pypicloud on https://192.168.99.100 with my web browser. Have added self-signed certificate to the nginx config as shown in #89.

Would be awesome to get his working!

**Comment by stevearc** [comment]
There is no need to register packages before uploading them with pypicloud. It's up to the admin to set the access control for who has read/write access to what packages. Try doing a `python setup.py sdist upload -r pypicloud`, making sure that you've set the permissions and access control correctly (http://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-default-read and http://pypicloud.readthedocs.io/en/latest/topics/access_control.html). If you still have trouble then please paste up your config file (minus any sensitive information)

**Comment by kevart** [comment]
Have added credentials in pypicloud.ini and skipped the register step, works for me now. Thx.
